### ISSUE TITLE
Remove travis config

### ISSUE THREAD

**Issue by reinhardt** [plone/Products.Archetypes#116]
Travis config is broken and jenkis is favoured over travis anyway. Remove travis config to reduce confusion.

**Comment by mauritsvanrees** [comment]
Travis was added because Archetypes will not be supported in Plone 6, but maybe someone will want to step up to support it, even though it won't be in core at that point anymore. Having a separate Travis config is useful then.

But I guess it is fine if we only test this in Jenkins.
Does anyone else want to comment?

**Comment by mauritsvanrees** [comment]
I have merged your PR.
Testing with Travis can be nice at the moment when Archetypes has left the core and is unsupported and someone wants to pick it up anyway.  Until that moment, it is a burden to keep both Jenkins and Travis passing.
